version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfiles/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ..:/usr/src/app:z
      - /usr/src/app/node_modules
    command: npm run dev
